/*
 * ClustersEnum.h
 *
 *  Created on: 29/lug/2014
 *      Author: Paolo Achdjian
 */

#ifndef CLUSTERSENUM_H_
#define CLUSTERSENUM_H_

namespace zigbee {

	enum ClustersId {
		INVALID_CLUSTER=-1,
		BASIC_CLUSTER=0,
		POWER_CONFIGURATION_CLUSTER=1,
		DEVICE_TEMPERATURE_CONFIG_CLUSTER=2,
		IDENTIFY_CLUSTER=3,
		GROUPS_CLUSTER=4,
		SCENE_CLUSTER=5,
		ON_OFF_CLUSTER=6,
		ON_OFF_CONF=7,
		LEVEL_CONTROL=8,
		ALARMS=9,
		TIME=0x0A,
		RSSI_LOCATION=0x0B,
		ANALOG_INPUT_BASIC=0x0C,
		ANALOG_OUTPUT_BASIC=0x0D,
		ANALOG_VAL_BASIC=0x0E,
		BINARY_INPUT_BASIC=0x0F,
		BINARY_OUTPUT_BASIC=0x10,
		BINARY_VALUE_BASIC=0x11,
		MULTISTATE_INPUT_BASIC=0x12,
		MULTISTATE_OUTPUT_BASIC=0x13,
		MULTISTATE_VALUE_BASIC=0x14,
		COMMISSIONING=0x15,
		ILLUMINANCE_MEASUREMENT=0x0400,
		ILLUMINANCE_LEVEL_SENSING=0x0401,
		TEMPERATURE_MEASUREMENT=0x0402,
		PRESSURE_MEASUREMENT=0x0403,
		FLOW_MEASUREMENT=0x0404,
		RELATIVE_HUMIDITY_MEASUREMENT=0x0405,
		OCCUPANCY_SENSING=0x0406

	};

}

#endif /* CLUSTERSENUM_H_ */
